### ISSUE TITLE
Guests in parks without entrance fee aren't counted

### ISSUE THREAD

**Issue by pencil** [terinjokes/openrct2-prometheus-exporter#3]

**Comment by terinjokes** [comment]
I meant to test that, but I guess all the parks I tested with have entrance fees.

https://github.com/terinjokes/openrct2-prometheus-exporter/blob/3726e35fcf45694c18678080eb1bde135d185e4b/index.js#L76

I was trying to avoid counting guests on the map but outside the entrance gates, but I guess that's a bad check. I'll remove the check.

**Comment by pencil** [comment]
That was quick, thanks!

**Comment by terinjokes** [comment]
I'm actively working on improving the plugin, so was easy to stash and push a fix for this. Sorry for the bug!
